image: padawanphysicist/python-guile

build:
  script:
    - ./bootstrap
    - ./configure
    - make
    - make check
    - make dist
  artifacts:
    paths:
      - guile-pyffi*.gz
  only:
    - tags
